################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Code \
DmxLibraries/DmxCommon \
DmxLibraries/DmxDevice \
DmxLibraries/DmxDriver \
InfineonLibraries/Configurations/Debug \
InfineonLibraries/Libraries/Infra/Platform/Tricore/Compilers \
InfineonLibraries/Libraries/Service/CpuGeneric/If \
InfineonLibraries/Libraries/Service/CpuGeneric/StdIf \
InfineonLibraries/Libraries/Service/CpuGeneric/SysSe/Bsp \
InfineonLibraries/Libraries/Service/CpuGeneric/SysSe/Comm \
InfineonLibraries/Libraries/Service/CpuGeneric/SysSe/General \
InfineonLibraries/Libraries/Service/CpuGeneric/SysSe/Math \
InfineonLibraries/Libraries/Service/CpuGeneric/SysSe/Time \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Asclin/Asc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Asclin/Lin \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Asclin/Spi \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Asclin/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/Icu \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/PwmBc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/PwmHl \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/TPwm \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cif/Cam \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cif/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cpu/CStart \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cpu/Irq \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cpu/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Cpu/Trap \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dma/Dma \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dma/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dsadc/Dsadc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dsadc/Rdc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dsadc/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dts/Dts \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Dts/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Emem/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Eray/Eray \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Eray/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Eth/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Fce/Crc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Fce/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Fft/Fft \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Fft/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Flash/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gpt12/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Tim/In \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Gtm/Trig \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Hssl/Hssl \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Hssl/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/I2c/I2c \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/I2c/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Iom/Driver \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Iom/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Msc/Msc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Msc/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Mtu/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Multican/Can \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Multican/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Port/Io \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Port/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Psi5/Psi5 \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Psi5/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Psi5s/Psi5s \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Psi5s/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Qspi/SpiSlave \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Qspi/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Scu/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Sent/Sent \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Sent/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Smu/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Src/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Stm/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Stm/Timer \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Vadc/Adc \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/Vadc/Std \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/_Impl \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/_Lib/InternalMux \
InfineonLibraries/Libraries/iLLD/TC26B/Tricore/_PinMap \
User \

